[package]
name = "radicle-seed"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
argh = "0.1.3"
chrono = "0.4"
thiserror = "1.0"
tokio = "0.2"
tracing = "0.1"
tracing-subscriber = "0.2"

[dependencies.librad]
git = "https://github.com/radicle-dev/radicle-link.git"
rev = "dee9a57948ca1a0eadee996108f3c441ce3641bf"

[dependencies.seed]
git = "https://github.com/radicle-dev/radicle-link.git"
rev = "dee9a57948ca1a0eadee996108f3c441ce3641bf"
